default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Overtime_development

test:
  <<: *default
  database: Overtime_test


production:
  <<: *default
  database: Overtime_production
  username: Overtime
  password: <%= ENV['OVERTIME_DATABASE_PASSWORD'] %>
